"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000/api/v1";
type Account = { id: string; name: string; email: string; roles: string[] };
type Booking = { _id: string; status: string; startsAt: string; endsAt: string; guests: number; destinationId?: { name: string; state: string }; guideId?: { userId?: { name: string } } };

export default function AccountPage() {
  const [account, setAccount] = useState<Account | null>(null);
  const [bookings, setBookings] = useState<Booking[]>([]);
  const [error, setError] = useState("");
  useEffect(() => { const token = sessionStorage.getItem("yv_access_token"); if (!token) { window.location.replace("/auth"); return; }
    const headers = { Authorization: `Bearer ${token}` };
    Promise.all([fetch(`${API}/auth/me`, { headers }), fetch(`${API}/bookings/mine`, { headers })]).then(async ([me, bookingResponse]) => { if (!me.ok) throw new Error("Your session has expired. Please sign in again."); const meData = await me.json(); setAccount(meData.data.user); if (bookingResponse.ok) { const bookingData = await bookingResponse.json(); setBookings(bookingData.data); } }).catch((reason) => { sessionStorage.removeItem("yv_access_token"); setError(reason instanceof Error ? reason.message : "Unable to load your account."); });
  }, []);
  function signOut() { sessionStorage.removeItem("yv_access_token"); window.dispatchEvent(new Event("yv-auth-change")); fetch(`${API}/auth/logout`, { method: "POST", credentials: "include" }).finally(() => window.location.assign("/")); }
  if (error) return <section className="mx-auto max-w-xl px-5 py-24"><div className="rounded-3xl border border-amber-200 bg-amber-50 p-8"><h1 className="font-serif text-3xl text-ink">Sign in required</h1><p className="mt-3 text-slate-600">{error}</p><Link href="/auth" className="mt-6 inline-block rounded-full bg-ink px-5 py-3 text-sm font-semibold text-white">Go to sign in</Link></div></section>;
  if (!account) return <section className="mx-auto max-w-7xl px-5 py-24"><p className="eyebrow text-plum">YATRA VERSE</p><p className="mt-4 font-serif text-4xl text-ink">Preparing your travel space…</p></section>;
  return <section className="mx-auto max-w-7xl px-5 py-14"><div className="flex flex-wrap items-end justify-between gap-6 border-b border-violet-100 pb-10"><div><p className="eyebrow text-plum">YOUR TRAVEL SPACE</p><h1 className="mt-4 font-serif text-5xl tracking-[-.04em] text-ink">Welcome, {account.name}.</h1><p className="mt-3 text-slate-600">Your journeys, local connections, and saved travel decisions in one place.</p></div><button onClick={signOut} className="rounded-full border border-violet-200 px-5 py-2.5 text-sm font-semibold text-plum transition hover:bg-lavender">Sign out</button></div><div className="mt-12 grid gap-6 lg:grid-cols-[1.35fr_.65fr]"><div className="rounded-[1.75rem] border border-violet-100 bg-white p-7 shadow-sm"><div className="flex items-center justify-between"><div><p className="eyebrow text-plum">YOUR BOOKINGS</p><h2 className="mt-3 font-serif text-3xl text-ink">Upcoming journeys</h2></div><Link href="/guides" className="text-sm font-semibold text-plum">Find a guide →</Link></div>{bookings.length ? <div className="mt-7 space-y-3">{bookings.map((booking) => <article key={booking._id} className="rounded-2xl border border-violet-100 p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-semibold text-ink">{booking.destinationId?.name ?? "Destination"}</h3><p className="mt-1 text-sm text-slate-500">{new Date(booking.startsAt).toLocaleDateString()} · {booking.guests} guest{booking.guests === 1 ? "" : "s"}</p></div><span className="h-fit rounded-full bg-lavender px-3 py-1 text-xs font-semibold capitalize text-plum">{booking.status.replace("_", " ")}</span></div></article>)}</div> : <div className="mt-7 rounded-2xl bg-[#faf8fd] p-6"><p className="font-medium text-ink">Your next story is still waiting.</p><p className="mt-2 text-sm leading-6 text-slate-600">When you book a verified local guide, the journey details will live here.</p></div>}</div><aside className="rounded-[1.75rem] bg-ink p-7 text-white"><p className="eyebrow text-[#cdb9fb]">ACCOUNT</p><h2 className="mt-4 font-serif text-3xl">Your YATRA profile</h2><dl className="mt-8 space-y-5 text-sm"><div><dt className="text-white/50">Email</dt><dd className="mt-1 font-medium">{account.email}</dd></div><div><dt className="text-white/50">Membership</dt><dd className="mt-1 font-medium capitalize">{account.roles.join(" · ")}</dd></div></dl>{account.roles.includes("guide") ? <Link href="/guide" className="mt-10 inline-flex border-b border-[#cdb9fb] pb-2 text-sm font-semibold text-white">Manage guide profile →</Link> : <Link href="/destinations" className="mt-10 inline-flex border-b border-[#cdb9fb] pb-2 text-sm font-semibold text-white">Explore destinations →</Link>}</aside></div></section>;
}
